name: markboard
region: sfo
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
services:
  - name: markboard
    github:
      branch: main
      repo: JamesTryand/markboard
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 3366
    instance_count: 1
    instance_size_slug: basic-xxs
envs:
  - key: ROOT_URL
    value: ${APP_URL}
  - key: PORT
    value: 3366
